export const projects = [
  {
    title: 'Lonely Slime',
    description: "Participated in a game making competition where my team and I had to create a game with the theme ‘Out Of Control’ and submit it 48 hours after the theme was announced. Our game came in top 100 in the number of ratings.",
      image: '/images/Lonely Slime.gif',
      tags: ['Unity ', 'C#'],
    source: 'https://sohwathismelvin.itch.io/lonely-slime',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Avoid It',
    description:"Created a simple arcade game similar to the Google Dinosaur game where players are supposed to avoid any incoming obstacles and survive as long as they can. Published the game to Google Playstore for free without any ads.",
    image: '/images/Avoid It.png',
    tags: ['Unity', 'C#'],
    source: 'https://play.google.com/store/apps/details?id=com.Gladeo.AvoidIt&hl=en_SG&gl=US',
    visit: 'https://github.com/Gladwinnnn/Avoid-It-',
    id: 1,
  },
  {
    title: 'Whack-A-Mole',
    description: "Created a simple arcade game similar to the classic Whack A Mole game where players are supposed to tap any moles they see to gain points within a minute. Published the game to Google Playstore for free without any ads.",
      image: '/images/Whacko Mole.png',
      tags: ['Unity', 'C#'],
    source: 'https://play.google.com/store/apps/details?id=com.Gladeo.WhackAMole&hl=en_SG&gl=US',
    visit: 'https://github.com/Gladwinnnn/Whack-A-Mole',
    id: 2,
  },
  {
    title: 'Mr B.Hell',
    description: "Participated in a game making competition where my team and I had to create a game with the theme ‘Death is only the beginning’ and submit it 10 days after the theme was announced.",
    image: '/images/Mr B Hell.png',
    tags: ['Unity', 'C#'],
    source: 'https://itch.io/jam/gamedevtv-jam-2022/rate/1553425',
    visit: 'https://github.com/Gladwinnnn/Bullet-Hell',
    id: 3,
  },
  {
    title: 'Leetcode Practice',
    description: "My Leetcode repository where I solve questions using Java. This repository was created for me to revise and keep track of my coding progress on leetcode in preparation for any coding interviews. Feel free to use this if you find it helpful.",
    image: '/images/leetcode.png',
    tags: ['Java'],
    source: 'https://leetcode.com/Gladeo/',
    visit: 'https://github.com/Gladwinnnn/Leetcode',
    id: 4,
  },
  {
    title: 'Portfolio Website',
    description: "This is a Portfolio project which highlights my relevant skills and experience. You are able to see all my past projects, work experiences, technology stack that I'm comfortable with as well as my personal achievements over the years.",
    image: '/images/Portfolio.png',
    tags: ['React.js'],
    source: 'https://gladwinneo.vercel.app/',
    visit: 'https://github.com/Gladwinnnn/Portfolio',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Entered Singapore Management University (SMU)', },
  { year: 2019, text: 'Worked as a IT System Developer at Onbrand Corporation', },
  { year: 2020, text: 'Worked as a Entrepreneur Associate at I.O.T Workz', },
  { year: 2021, text: 'Worked as a Software Engineer Intern at Bank of Singapore', },
  { year: 2022, text: 'Working as a Associate Solution Architect at Amazon Web Services', },
];